package vista;

import controlador.*;
import java.awt.Color;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import modelo.Parcela;
/**
 *
 * @author alexoterof
 */
public class FramePrincipal extends javax.swing.JFrame {
	//NOTAS
	//Se permite eliminar una reserva sin coste se hace en el mismo dia de entrada "por si el usuario se equivoca al introducir datos". En ese caso se hace checkOut y se cobran 0€. No se registra.
	private static final int ANCHO = 8;
	private static final int ALTO = 10;
	private static JButton[][] arrayParcelas;
	ParametrosIO parametros;
	Camping camping;
	
	/**
	 * Creates new form FramePrincipal
	 */
	public FramePrincipal() {
		parametros = new ParametrosIO();
		parametros.actualizaParametros();
		camping = new Camping(parametros);
		camping.instanciaParcelas();
		
		arrayParcelas = new JButton[ANCHO][ALTO];
		
		initComponents();
		iniciaBotones();
		
		
	}
	private void iniciaBotones(){
		for (int j = 0; j < ALTO; j++) {
			for (int i = 0; i < ANCHO; i++) {
				int casilla = i+1 + 8*j;
				arrayParcelas[i][j] = new JButton();
				arrayParcelas[i][j].setFont(new java.awt.Font("Tahoma", 0, 36));
				arrayParcelas[i][j].addMouseListener(new java.awt.event.MouseAdapter() {
					@Override
					public void mouseClicked(java.awt.event.MouseEvent evt) {
						camping.parcelaClickada(evt);
						}
					});
				arrayParcelas[i][j].setName(casilla + "");
				arrayParcelas[i][j].setBackground(Color.LIGHT_GRAY);
				arrayParcelas[i][j].setText(casilla + "");
				GridParcelas.add(arrayParcelas[i][j]);
			}
		}
	}
	
	public static void actualizaInterfaz(Map<Integer,Parcela> parcelas){
		for(JButton[] arrayBotones : arrayParcelas){
			for (JButton boton : arrayBotones){
				if(parcelas.get(Integer.parseInt(boton.getName())).isOcupada()){
					boton.setBackground(Color.red);
				}else{
					boton.setBackground(Color.LIGHT_GRAY);
				}
			}
		}
	}
	
	public static void muestraFactura(Double precio){
		JOptionPane.showMessageDialog(null, "El total asciende a " + precio);
	}
	
	public static String obtenDNI(){
		return JOptionPane.showInputDialog("Introduce el DNI del inquilino responsable");
	}
	
	public static String obtenNumAdultos(){
		return JOptionPane.showInputDialog("Introduce el numero de adultos");
	}
	
	public static void muestraError(String error){
		JOptionPane.showMessageDialog(null, error);
	}
	
	
	
	
	/**
	 * This method is called from within
	 * the constructor to initialize the
	 * form. WARNING: Do NOT modify this
	 * code. The content of this method
	 * is always regenerated by the Form
	 * Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        GridParcelas = new javax.swing.JPanel();
        Botonero = new javax.swing.JPanel();
        parametrosBoton = new javax.swing.JButton();
        ayudaBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloLabel.setPreferredSize(new java.awt.Dimension(800, 100));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(166, 45, 77));
        jLabel1.setText("Camping Del Sol");

        javax.swing.GroupLayout tituloLabelLayout = new javax.swing.GroupLayout(tituloLabel);
        tituloLabel.setLayout(tituloLabelLayout);
        tituloLabelLayout.setHorizontalGroup(
            tituloLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLabelLayout.createSequentialGroup()
                .addContainerGap(316, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        tituloLabelLayout.setVerticalGroup(
            tituloLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLabelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(tituloLabel, java.awt.BorderLayout.PAGE_START);

        GridParcelas.setPreferredSize(new java.awt.Dimension(800, 600));
        GridParcelas.setLayout(new java.awt.GridLayout(10, 8));
        getContentPane().add(GridParcelas, java.awt.BorderLayout.CENTER);

        Botonero.setPreferredSize(new java.awt.Dimension(800, 100));

        parametrosBoton.setText("jButton1");

        ayudaBoton.setText("jButton2");

        salirBoton.setText("jButton3");

        javax.swing.GroupLayout BotoneroLayout = new javax.swing.GroupLayout(Botonero);
        Botonero.setLayout(BotoneroLayout);
        BotoneroLayout.setHorizontalGroup(
            BotoneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotoneroLayout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(parametrosBoton)
                .addGap(18, 18, 18)
                .addComponent(ayudaBoton)
                .addGap(18, 18, 18)
                .addComponent(salirBoton)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        BotoneroLayout.setVerticalGroup(
            BotoneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotoneroLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(BotoneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parametrosBoton)
                    .addComponent(ayudaBoton)
                    .addComponent(salirBoton))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        getContentPane().add(Botonero, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line
	 * arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FramePrincipal().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Botonero;
    private javax.swing.JPanel GridParcelas;
    private javax.swing.JButton ayudaBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton parametrosBoton;
    private javax.swing.JButton salirBoton;
    private javax.swing.JPanel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
